FROM nginx
ADD ./certs/ads-ci.geocent.com.key /etc/ssl/ads-ci.geocent.com.key
ADD ./certs/bundle.crt /etc/ssl/bundle.crt
ADD ./certs/dhparams.pem /etc/ssl/dhparams.pem
ADD ./default.conf /etc/nginx/conf.d/default.conf