#18fdb:
#  extends:
#    file: devops/containers/db/db-service.yml
#    service: postgres
#18fapp:
#  extends:
#    file: devops/containers/app/app-service.yml
#    service: node
18fweb:
  extends:
    file: devops/containers/app/web/web-service.yml
    service: nginx
  volumes:
    - ./client/dist:/usr/share/nginx/html

