18fdb:
  extends:
    file: devops/containers/db/db-service.yml
    service: postgres
18fapp:
  extends:
    file: devops/containers/app/app-service.yml
    service: node
18fweb:
  extends:
    file: devops/containers/web/web-service.yml
    service: nginx

