# https://registry.hub.docker.com/_/nginx/

nginx:
  image: nginx
  ports:
    - "8005:80"
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./default.conf:/etc/nginx/conf.d/default.conf:ro
